# X-RTA_3.0 deploy
name: X-RTA_3.0 deploy

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
       
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - working-directory: ./Map
      run: pwd
    - name: Zip Map
      working-directory: ./Map
      run: zip -r X-RTA_3.0.h5m .
    - run: mkdir -p path/to/artifact
    - name: Copy Map
      run: cp -r Map/X-RTA_3.0.h5m path/to/artifact
    - name: Copy Exe
      run: cp -r Exe/H5_Game.exe path/to/artifact
    - uses: actions/upload-artifact@v3
      with:
        name: X-RTA_3.0
        path: path/to/artifact/
