# Publish GitHub workflow artifacts tutorial example
name: Publish GitHub Actions Artifacts Example

on:
  push:
    branches: [ main ]

jobs:
       
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Create Artifact Folder
      run: New-Item -Path '${{ github.workspace }}' -Name "Artifacts" -ItemType "directory"
    - name: Copy Scripts
      run: Copy './Map/scripts/' '${{ github.workspace }}/Artifacts/scripts'
    - name: Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        path: ${{ github.workspace }}/Artifacts
        name: ${{ github.run_number }}
        
