# Publish GitHub workflow artifacts tutorial example
name: Publish GitHub Actions Artifacts Example

on:
  push:
    branches: [ main ]

jobs:
       
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Step 3 - Use the Upload Artifact GitHub Action
      uses: actions/upload-artifact@v3
      with: 
        name: assets-for-download
        path: ${{ github.workspace }}/Map/scripts
        
