# Publish GitHub workflow artifacts tutorial example
name: Publish GitHub Actions Artifacts Example

on:
  push:
    branches: [ main ]

jobs:
       
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Zip Folder
      run: zip -r release.zip ./Map/scripts
    - name: Step 3 - Use the Upload Artifact GitHub Action
      uses: actions/upload-artifact@v3
      with: 
        name: assets-for-download
        path: release.zip
    - name: Release to Github
      run: echo "Release"
